let
    // ... your previous steps above ...

    Keywords = {"[word1]", "[word2]"},
    AddHasKeywordNum = Table.AddColumn(
        #"[Previous Step]",
        "[ColumnName]",
        each if
            List.AnyTrue(
                List.Transform(
                    Keywords,
                    (k) => Text.Contains(Text.From([YourColumn]), k, Comparer.OrdinalIgnoreCase)
                )
            )
        then 1 else 0,
        Int64.Type
    )

in
//....
